import { CSV2Struct } from "./index";

test('parsed', () => {
	expect(CSV2Struct('a,b,c,d,e,f,g\n1,x,1.1,true,2022-01-01T00:00:00Z,2022-01-01,').struct).toBe(`type AutoGenerated sturct {
	A int \`csv:"a"\`
	B string \`csv:"b"\`
	C float64 \`csv:"c"\`
	D bool \`csv:"d"\`
	E time.Time \`csv:"e"\`
	F string \`csv:"f"\`
	G interface{} \`csv:"g"\`
}`)
})

test('error', () => {
	expect(CSV2Struct('"a"\n1').error?.message).toBe('CSV parse error.')
})
