import { CSV2Struct } from "./index";

test('a', () => {
	expect(CSV2Struct('a,b\n1,2\n3,4')).toBe('type AutoGenerated sturct {\n\tA int `csv:"a"`\n\tB int `csv:"b"`\n}')
	expect(CSV2Struct('"a"\n1')).toBe('type AutoGenerated sturct {\n\tA int `csv:"a"`\n}')
})
